name: 'RelativeCI agent upload artifacts'
description: 'Upload RelativeCI artifacts'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  webpackStatsFile:
    description: 'Path to your local webpack stats file'
    required: false
    default: './webpack-stats.json'
  artifactName:
    description: 'Artifact to download when running in workflow_run'
    required: false
    default: 'relative-ci-artifacts'
  artifactWebpackStatsFile:
    description: 'Artifact webpack stats file name'
    required: false
    default: weebpack-stats.json
  retentionPeriod:
    description: actions/upload-artifact retention-period value
    required: false
    default: 90

runs:
  using: "composite"
  steps:
    - name: Prepare artifacts folder
      id: artifacts-dir
      run: |
        TMP_ARTIFACT_DIR=$RUNNER_TEMP/$ARTIFACT_NAME
        mkdir $TMP_ARTIFACT_DIR
        cp $WEBPACK_STATS_FILE $TMP_ARTIFACT_DIR/$ARTIFACT_WEBPACK_STATS_FILE
        echo "::set-output name=tmpArtifactDir::${TMP_ARTIFACT_DIR}"
      shell: bash
      env:
        WEBPACK_STATS_FILE: ${{ inputs.webpackStatsFile }}
        ARTIFACT_NAME: ${{ inputs.artifactName }}
        ARTIFACT_WEBPACK_STATS_FILE: ${{ inputs.artifactWebpackStatsFile }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.artifactName }}
        path: ${{ steps.artifacts-dir.outputs.tmpArtifactDir }}
        retention-period: ${{ inputs.retentionPeriod }}
